sudo: required
language: go
addons:
  apt:
    packages:
    # needed for the nfpm pipe:
    - rpm
    # needed for the snap pipe:
    - snapd
go:
- 1.12.x
install:
# needed for the snap pipe:
- sudo snap install snapcraft --classic
- make deps
- make testacc
script:
- make build
branches:
  only:
  - master
deploy:
- provider: script
  skip_cleanup: true
  script: curl -sL https://git.io/goreleaser | bash
  on:
    tags: true
    condition: $TRAVIS_OS_NAME = linux
env:
  global:
  # needed for the snap pipe:
  - PATH=/snap/bin:$PATH
  - secure: uxSzxRYWTQxcZ7MNIsBJzH/+KObg8ubX0cjg0RHv05svJMlX0jMgnoUP+CIo3SdWCG2dgJgcWcP2H9R/cZPAc/ZIx4dpyHi13dLbIQ/Vy3FOQIlAGcbhnteUaMlN3vBcBnZFE2W/zjRRTrBkkRTfQ1gP6uUa+cfsjnRHpAyRuOEb4hk+T+Pb2X+5uLDQazlW+rMEBsr2kqBQFinV87YhqfPQxKxWRfgO8b8JSS1TMSKqGiyrI14T0BQvN3f8PRFIuKNvdRMPdl1+fJDfl3VLB5a9ajPnVWcFaAD0cCkpDMMnvxLg00VbY+3wvXNKEj3H/uW5xF0Q6mVeku41C38XEtM25MFqH5kZEVwBuoAxBm6j5x9j8yagNZeDpC4FJKdGTtbNX6gThP26i0yGeR+caP4mqMzDWIceDkNyTTkHSwqrem0SgmDutfqMurV+OkS9leQ4N7EIW0JNb/5Tusy9HI7qpR0aXYxaSokeftSPS3p2uNJg8v4IQxz98uJx94HduNc+WETDVe4dKSYeZwcvb6zRFSF/YQA96BemR8o1dg80/Bn6eUALoAzFwK9KdXFkSKNMfPhww5CTa/iRHDk06jwn6eR21AneQg1VDfoWoNQiCMw4aeH/h1k2MxlNUPC0Rd7MJU1/IKeatZSG+miFDoUhDXltbXKXrh0tVGG8Bd0=
  - secure: 425AGhHu9NPENvWvDtUd06RXypTQzH7A3mF/Ti9pyklEoI8IRPzlro8M3kZ7bPuTHl17oMo1aBhE4E8Neq2J14AQtsvCq6qQflxRM/nLFAYayf0gwOlxdCWnOGbIQBjksnU2AzPOumluP951fU9+6hR5vDJEYxgmK5SIpvEaNpfW0/6rIS2kNnRrlsnu+D/lTaF9FAMiVM78kueYe5cGrhrjkr4I1vemq1j5IRvEKRNVdz6HRLF76tpFmfAEp9fVfmopRo6EpODp4ghbW9kU3c/GMQRVkDsk1jvdONa79Ttkewj/aB1FsG4u/yzjl+XeF5XJ/Mu0rxTJgOcQBNSeOGuJjt2UPhCtLmBd5XaGErjrE6VFaCW2BVmYgCzOsuVTE3KGg0goz0LvVttAFsrAJKp/LKMY/zX8djS3LykXjbxhlHzrU0YNsD7p/v2haHl3qURHzOveCVwET0oGSDuRg+bHYxyNXYID9x6k9aVkzdy1ZdTUH/88qbf0hqw9HUe/iNBR7AL+PQKvQ0mRYDqbeCN0RIoFNm3kWK4QS5k7lMnka2217Y34c91kLMHzRUxhc/RaaQfpy1ENnRTT165P9HpluF8CfdcG2UrXbTwekkmInleGL3Zbn3g8+HE+M8kap7Ma6O8+Ez2IQCxdMcmXWxvUluiqrivzYHQp70903hs=
  - secure: MIixEYXOOW2QxVjVMzlzQ83rmhfIc/xM/NCxzYnv4pjj3QIPgs+Q/3gxwBUmWnbCbM2H6U6E4ZhJz674/b9v0+TjqiQO4gMdnQvvXsRBRM/jAoJ3SIt/ZRx9ERoeoATU6vzB3IyDkdHbKAeVRL6lbF3wnVLAz2AfZDt007ZdJDc/VrkB/le8KZEDAtu5mRHgErNZqgk4mfumnhhLb8JDVJaJoZdxcPqS7tMBj2OA4Omc8HJ1tHIpJ/Yg8J1seA9vJom3PJbJ3ruFxNP964BlyxXAWk+nGRLyIzGQYHgXZAJUfsTL0xdkvjWzfcPQzLvF85dzj2Y8Pt604+xajPf4znfIAvX4Clwstg/GMuuiQj8oqk6z8ZAQG+gO4ghi9En/ePLBaWkwiN3tixzdpL1Zt7N+tfk5nArf9sfX35K6F6qIsk8rGV3VmWaey147XMgLgFXBPpzs4EBni2ldu5rdriD4M/yujM7xqekTENDkrdIbD+5JugyxDQdEbxh71WbW++ZicrndVNGYZKExKnTIjpKBjJfb6fT7iLyfkD9ng7fEkDdmHhyTbXGpQQQ9M5BlSUXumwcgMDyWSOnPdi2GiiKfC9NjjNYzFZIPi7702N+bleqI5hRMwTnccWqNcPi5hdjAW+k58HzDrF3vhBQB500eNVoC9b/OHP4Yhc1Lst8=
  - secure: 4x7C9C5QFm1P3cuDODYC6iUjkqrCIj3RActiZXsobvh2abyuFkU+PkJhkiETsJ3hwJ5WaDQnbH2RWpDFj0PcwUzmcNqa2bHVsKvj/jxTp3fgApjI9aPWNO58xHxBEFVVh4AK+nrPwR27Ep0Kbj0oiSgrBcKki6LvhxR+QcsRrt8W/rZT7wfaxwPCo6kRydAA1HsFKwXnwdD3toUuo2Q6OW3creR5BX3YPRfWHMPyJOhY9idL3aS0HTqL4tqA6VvANzMKub6GfJypxe15eWI9uQ0SRHoBUfAScaHyZSEfzy1fLro2Rle3R1MMB/L5kW0LTbBRHRUHsZoBWrxQBO36pLgdbNsLLIgUdQJZTC25hxjaQXHKG2J0uEh/d62EQuPyq5Ev3KiLNgK48y2LwZ+KiWxvy8//nTGVGAAnWWvjQdQ8awWFu8PI1nLwgvz9QLJn4FYEF+v1lE628lz/0b/bJXuBa4tWGUaBNnwpVm/jfzgllE27Givk5FJZ0zRZJCIn3xtygFZs29mYzqDQss8hzjzj/3sBdVbxRsYkgQzE5LGs7yrP5cdLq2I17FrDg6t9JuJcI1tM7KCdNF94Udc+YiahtP/y3RnaZFd6dMVQRYELAuPwVOy9MxOEEndBUoB0+uC9hTrYTIPIIsL3HcTV6TcH07djTzeOel+YuPWqBpM=
