required = ["github.com/mitchellh/gox"]

[[constraint]]
  branch = "master"
  name = "github.com/articulate/oktasdk-go"

[[constraint]]
  branch = "wait-for-rate-limit"
  name = "github.com/okta/okta-sdk-golang"
  source = "https://github.com/articulate/okta-sdk-golang.git"

[[constraint]]
  version = "0.11.11"
  name = "github.com/hashicorp/terraform"

[[constraint]]
  name = "github.com/dghubble/sling"
  version = "1.1.0"

[[constraint]]
  name = "github.com/peterhellberg/link"
  version = "1.0.0"

[[constraint]]
  name = "github.com/mitchellh/gox"
  branch = "master"

[prune]
  go-tests = true
  unused-packages = true
